version: 0.0
os: linux
hooks:
   BeforeInstall:
     - location: scripts/before_install.sh
       timeout: 60
       runas: root
   AfterInstall:
     - location: scripts/after_install.sh
       timeout: 60
       runas: root
